name: chat_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.3.2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.2.15
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  faker: ^2.0.0
  stream_chat_flutter_core: ^4.1.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

